Update busybox, python, mesa builds. Update LLVM to 11.0.0rc2.

diff --git a/core/busybox/build b/core/busybox/build
--- a/core/busybox/build
+++ b/core/busybox/build
@@ -1,9 +1,10 @@
 #!/bin/sh -e
 
 # clang/llvm seems to produce binaries which segfault if used with -Ox
-# Remove that option if present
-CFLAGS=$(echo $CFLAGS | sed -r 's/-O(0|1|2|3|s|fast)//g')
-CXXFLAGS=$(echo $CXXFLAGS | sed -r 's/-O(0|1|2|3|s|fast)//g')
+# or -lto options. Use plain build flags until resolved. 
+unset CFLAGS
+unset LDFLAGS
+unset CXXFLAGS
 
 # CFLAGS cleanup
 # See http://lists.busybox.net/pipermail/busybox/2019-October/087558.html
@@ -20,6 +21,18 @@ done
 # This excludes utilities which require 'suid' to function.
 make CC="${CC:-cc}" HOSTCC="${CC:-cc}"
 make CONFIG_PREFIX="$1/usr" install
+
+
+# Test the built binary to check if it works.
+# Have had clang build binaries without complaining,
+# but they segfault when run!
+BUILDTEST=$(busybox echo 'test')
+if [ $BUILDTEST != "test" ]
+then
+   echo "Build output execution fails"
+   exit 1
+fi
+
 
 # Rename the binary temporarily.
 mv "$1/usr/bin/busybox" "$1/usr/bin/busybox-nosuid"
