[file] Update to 5.42

diff --git a/extra/file/build b/extra/file/build
--- a/extra/file/build
+++ b/extra/file/build
@@ -1,5 +1,12 @@
 #!/bin/sh -e
 
+if [ "$KISS_ROOT" ]; then
+    if [ ! -d /var/db/kiss/installed/file ]; then
+        echo "Error: to cross-build file, you need to have it on your build machine first."
+        exit 1
+    fi
+fi
+
 ./configure \
     --prefix=/usr \
     --build=$KISS_XBUILD_TRIPLE \
